services:
  rollercoin_frontend:
    container_name: rollercoin_frontend
    image: ${IMAGE_TAG}
    restart: always
    networks:
      - global-rollercoin-network

networks:
  global-rollercoin-network:
    external: true