server {
    listen 80;
    server_name localhost;

    # KÖK DİZİNİ BURAYA ALIYORUZ (Hepsine hükmeder)
    root /usr/share/nginx/html;
    index index.html;

    # Performans Ayarları
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    # Sıkıştırma
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
        absolute_redirect off;
        try_files $uri $uri/index.html /index.html;
    }

    # Resim Önbellekleme
    location ~* \.(jpg|jpeg|png|gif|ico|webp|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # sw.js bloğu artık yukarıdaki root'u kullanacak
    location = /sw.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
    }
}