const fs = require('node:fs');
const path = require('node:path');
const languages = ['en', 'tr', 'ru', 'de', 'es', 'fr', 'pt', 'id', 'zh', 'cs'];
// Paraphrased mechanics from the verified articles in hamsterAbilityGuides.ts.
// Column order follows languages above. This script never replaces catalog data.
const ui = {
  animationsPendingWithIdle: [
    'The walking animation and idle preview are available for now. All animations will be added when the hamster joins the game.',
    'Şimdilik yürüyüş animasyonu ve idle önizlemesi mevcut. Hamster oyuna eklendiğinde tüm animasyonlar eklenecek.',
    'Пока доступны анимация ходьбы и анимация ожидания. Все анимации будут добавлены, когда хомяк появится в игре.',
    'Vorerst sind Laufanimation und Leerlaufvorschau verfügbar. Alle Animationen werden ergänzt, sobald der Hamster ins Spiel kommt.',
    'Por ahora están disponibles la animación de caminar y la vista en reposo. Se añadirán todas las animaciones cuando el hámster llegue al juego.',
    'L’animation de marche et l’aperçu au repos sont disponibles pour le moment. Toutes les animations seront ajoutées lorsque le hamster arrivera dans le jeu.',
    'Por enquanto, a animação de caminhada e a prévia em repouso estão disponíveis. Todas as animações serão adicionadas quando o hamster entrar no jogo.',
    'Saat ini animasi berjalan dan pratinjau diam tersedia. Semua animasi akan ditambahkan ketika hamster hadir di dalam game.',
    '目前提供行走动画和待机预览。仓鼠加入游戏后将添加全部动画。',
    'Zatím jsou dostupné animace chůze a náhled v klidu. Všechny animace budou přidány, až se křeček objeví ve hře.'
  ],
  animationsPending: [
    'Only the walking animation is available for now. All animations will be added when the hamster joins the game.',
    'Şimdilik yalnızca yürüyüş animasyonu mevcut. Hamster oyuna eklendiğinde tüm animasyonlar eklenecek.',
    'Пока доступна только анимация ходьбы. Все анимации будут добавлены, когда хомяк появится в игре.',
    'Vorerst ist nur die Laufanimation verfügbar. Alle Animationen werden ergänzt, sobald der Hamster ins Spiel kommt.',
    'Por ahora solo está disponible la animación de caminar. Se añadirán todas las animaciones cuando el hámster llegue al juego.',
    'Seule l’animation de marche est disponible pour le moment. Toutes les animations seront ajoutées lorsque le hamster arrivera dans le jeu.',
    'Por enquanto, apenas a animação de caminhada está disponível. Todas as animações serão adicionadas quando o hamster entrar no jogo.',
    'Saat ini hanya animasi berjalan yang tersedia. Semua animasi akan ditambahkan ketika hamster hadir di dalam game.',
    '目前仅提供行走动画。仓鼠加入游戏后将添加全部动画。',
    'Zatím je dostupná pouze animace chůze. Všechny animace budou přidány, až se křeček objeví ve hře.'
  ],
  passive: ['Passive abilities', 'Pasif yetenekler', 'Пассивные способности', 'Passive Fähigkeiten', 'Habilidades pasivas', 'Capacités passives', 'Habilidades passivas', 'Kemampuan pasif', '被动技能', 'Pasivní schopnosti'],
  ultimate: ['Ultimate ability', 'Nihai yetenek', 'Ультимативная способность', 'Ultimative Fähigkeit', 'Habilidad definitiva', 'Capacité ultime', 'Habilidade suprema', 'Kemampuan ultimate', '终极技能', 'Ultimátní schopnost'],
  overcharged: ['Overcharged ultimate', 'Kademeli nihai yetenek', 'Многоуровневый ультимейт', 'Mehrstufige ultimative Fähigkeit', 'Definitiva por niveles', 'Capacité ultime à paliers', 'Suprema por níveis', 'Ultimate bertingkat', '分级终极技能', 'Víceúrovňová ultimátní schopnost'],
  activation: ['Charge, then activate before an Expedition.', 'Şarj ettikten sonra sefer öncesinde etkinleştirilir.', 'Зарядите и активируйте перед экспедицией.', 'Aufladen und vor einer Expedition aktivieren.', 'Cárgala y actívala antes de una expedición.', 'Chargez-la et activez-la avant une expédition.', 'Carregue e ative antes de uma expedição.', 'Isi daya lalu aktifkan sebelum Ekspedisi.', '充能后在远征前激活。', 'Nabijte a aktivujte před expedicí.'],
  activationAfter: ['Charge, then use after a successful Expedition.', 'Şarj ettikten sonra başarılı seferin sonunda kullanılır.', 'Зарядите и используйте после успешной экспедиции.', 'Aufladen und nach erfolgreicher Expedition verwenden.', 'Cárgala y úsala tras una expedición exitosa.', 'Chargez-la et utilisez-la après une expédition réussie.', 'Carregue e use após uma expedição bem-sucedida.', 'Isi daya lalu gunakan setelah Ekspedisi berhasil.', '充能后在成功远征结束时使用。', 'Nabijte a použijte po úspěšné expedici.'],
  officialBlog: ['Official blog', 'Resmî blog', 'Официальный блог', 'Offizieller Blog', 'Blog oficial', 'Blog officiel', 'Blog oficial', 'Blog resmi', '官方博客', 'Oficiální blog'],
  source: ['Official explanation', 'Resmî açıklama', 'Официальное описание', 'Offizielle Erklärung', 'Explicación oficial', 'Explication officielle', 'Explicação oficial', 'Penjelasan resmi', '官方说明', 'Oficiální vysvětlení'],
  example: ['Blog example', 'Blogdaki örnek', 'Пример из блога', 'Beispiel aus dem Blog', 'Ejemplo del blog', 'Exemple du blog', 'Exemplo do blog', 'Contoh dari blog', '博客示例', 'Příklad z blogu'],
};
const descriptions = {
  remoteBonusUltimate: [
    'While Cuscuz is alive on an Expedition, grants a temporary room bonus equal to his total stats ×2%. Uses the original Expedition duration; Speed-Ups and time-reduction abilities do not shorten the bonus. Recharge: {{charge}} points.',
    'Cuscuz seferde hayattayken toplam statı ×%2 kadar geçici oda bonusu verir. Bonus orijinal sefer süresini kullanır; hızlandırmalar ve süre azaltan yetenekler bonus süresini kısaltmaz. Şarj: {{charge}} puan.',
    'Пока Cuscuz жив в экспедиции, даёт временный бонус комнаты: сумма характеристик ×2%. Длительность равна исходному времени экспедиции; ускорения и сокращающие время способности её не уменьшают. Заряд: {{charge}} очков.',
    'Solange Cuscuz auf einer Expedition lebt, gewährt er einen temporären Raumbonus: Gesamtwerte ×2%. Die ursprüngliche Expeditionsdauer gilt; Beschleuniger und zeitverkürzende Fähigkeiten verkürzen den Bonus nicht. Aufladen: {{charge}} Punkte.',
    'Mientras Cuscuz esté vivo en una expedición, concede un bonus temporal de sala igual a sus estadísticas totales ×2%. Usa la duración original; los aceleradores y habilidades que reducen el tiempo no acortan el bonus. Recarga: {{charge}} puntos.',
    'Tant que Cuscuz est vivant en expédition, accorde un bonus temporaire de salle égal au total de ses stats ×2 %. La durée originale s’applique ; les accélérateurs et capacités réduisant le temps ne raccourcissent pas le bonus. Recharge : {{charge}} points.',
    'Enquanto Cuscuz estiver vivo em uma expedição, concede um bônus temporário de sala igual à soma dos atributos ×2%. Usa a duração original; aceleradores e habilidades de redução de tempo não encurtam o bônus. Recarga: {{charge}} pontos.',
    'Selama Cuscuz hidup dalam Ekspedisi, memberikan bonus ruangan sementara sebesar total atribut ×2%. Menggunakan durasi Ekspedisi asli; percepatan dan kemampuan pengurangan waktu tidak memperpendek bonus. Isi ulang: {{charge}} poin.',
    'Cuscuz在远征中存活时，提供属性总和×2%的临时房间加成。持续时间按原始远征时长计算；加速道具和缩短时间的技能不会缩短加成。充能：{{charge}}点。',
    'Dokud je Cuscuz v expedici naživu, poskytuje dočasný bonus místnosti ve výši součtu atributů ×2 %. Platí původní délka expedice; zrychlení a schopnosti zkracující čas bonus nezkracují. Dobití: {{charge}} bodů.'
  ],
  experience: [
    'Increases the XP this hamster earns from Expeditions by the displayed percentage.', 'Bu hamsterın seferlerden kazandığı deneyimi belirtilen yüzde kadar artırır.', 'Увеличивает опыт этого хомяка от экспедиций на указанный процент.', 'Erhöht die Expeditions-EP dieses Hamsters um den angegebenen Prozentsatz.', 'Aumenta la XP que este hámster gana en expediciones en el porcentaje indicado.', 'Augmente les XP gagnés en expédition par ce hamster du pourcentage indiqué.', 'Aumenta a XP deste hamster nas expedições pela porcentagem indicada.', 'Meningkatkan XP hamster ini dari Ekspedisi sesuai persentase yang ditampilkan.', '按所示百分比增加该仓鼠从远征中获得的经验。', 'Zvyšuje zkušenosti tohoto křečka z expedic o uvedené procento.'
  ],
  survival: [
    'Adds the signed percentage directly to the final survival chance. A negative value reduces it.', 'İşaretli yüzdeyi doğrudan nihai hayatta kalma olasılığına ekler. Negatif değer olasılığı azaltır.', 'Указанный процент напрямую прибавляется к шансу выживания. Отрицательное значение снижает его.', 'Addiert den Wert direkt zur Überlebenschance. Ein negativer Wert senkt sie.', 'Suma el porcentaje directamente a la probabilidad final de supervivencia. Un valor negativo la reduce.', 'Ajoute le pourcentage directement à la probabilité finale de survie. Une valeur négative la réduit.', 'Soma a porcentagem diretamente à chance final de sobrevivência. Um valor negativo a reduz.', 'Menambahkan persentase langsung ke peluang bertahan hidup akhir. Nilai negatif menguranginya.', '将带符号的百分比直接加到最终生存概率上，负值会降低概率。', 'Přičítá uvedené procento přímo ke konečné šanci na přežití. Záporná hodnota ji snižuje.'
  ],
  rest: [
    'Changes rest time after an Expedition by the displayed percentage; a negative value means less waiting.', 'Sefer sonrası dinlenme süresini belirtilen yüzde kadar değiştirir; negatif değer beklemeyi kısaltır.', 'Меняет время отдыха после экспедиции на указанный процент; отрицательное значение сокращает ожидание.', 'Ändert die Ruhezeit nach einer Expedition. Negative Werte verkürzen die Wartezeit.', 'Modifica el descanso tras una expedición según el porcentaje indicado; los valores negativos lo acortan.', 'Modifie le repos après une expédition ; une valeur négative réduit l’attente.', 'Altera o descanso após a expedição; um valor negativo reduz a espera.', 'Mengubah waktu istirahat setelah Ekspedisi; nilai negatif memperpendek waktu tunggu.', '按所示百分比调整远征后的休息时间，负值表示减少等待。', 'Mění odpočinek po expedici; záporná hodnota zkracuje čekání.'
  ],
  loot: [
    'Changes Expedition loot by the displayed percentage. A negative value sacrifices loot for another build benefit.', 'Sefer ganimetini belirtilen yüzde kadar değiştirir. Negatif değer, başka bir yapı avantajı karşılığında ganimeti azaltır.', 'Меняет добычу на указанный процент. Отрицательное значение уменьшает добычу ради другого бонуса сборки.', 'Ändert die Expeditionsbeute. Negative Werte tauschen Beute gegen einen anderen Build-Vorteil.', 'Modifica el botín de expedición. Los valores negativos sacrifican botín por otra ventaja.', 'Modifie le butin d’expédition. Une valeur négative échange du butin contre un autre avantage.', 'Altera o saque da expedição. Valores negativos sacrificam saque por outra vantagem.', 'Mengubah jarahan Ekspedisi. Nilai negatif mengorbankan jarahan demi manfaat build lain.', '调整远征战利品；负值表示减少战利品以换取其他配置优势。', 'Mění kořist z expedice. Záporná hodnota obětuje kořist za jinou výhodu sestavy.'
  ],
  duration: [
    'Changes Expedition duration by the displayed percentage; negative values finish sooner, positive values take longer.', 'Sefer süresini belirtilen yüzde kadar değiştirir; negatif değer daha erken, pozitif değer daha geç bitirir.', 'Меняет длительность экспедиции; отрицательные значения ускоряют, положительные замедляют.', 'Ändert die Expeditionsdauer: Negative Werte verkürzen, positive verlängern sie.', 'Modifica la duración: los valores negativos la acortan y los positivos la alargan.', 'Modifie la durée : les valeurs négatives la réduisent, les positives l’allongent.', 'Altera a duração: valores negativos encurtam e positivos prolongam a expedição.', 'Mengubah durasi Ekspedisi; nilai negatif mempercepat dan nilai positif memperpanjang.', '调整远征时长：负值缩短，正值延长。', 'Mění dobu expedice: záporné hodnoty ji zkracují, kladné prodlužují.'
  ],
  overtime: [
    'The displayed chance to skip rest after a successful Expedition and immediately start another.', 'Başarılı seferden sonra dinlenmeyi atlayıp hemen yeni sefere başlama ihtimalidir.', 'Указанный шанс пропустить отдых после успешной экспедиции и сразу начать следующую.', 'Chance, nach einer erfolgreichen Expedition die Ruhezeit zu überspringen.', 'Probabilidad de saltarse el descanso tras una expedición exitosa y comenzar otra.', 'Chance de sauter le repos après une expédition réussie et d’en commencer une autre.', 'Chance de pular o descanso após uma expedição bem-sucedida e iniciar outra.', 'Peluang melewati istirahat setelah Ekspedisi berhasil dan langsung memulai berikutnya.', '成功远征后跳过休息并立即开始下一次远征的概率。', 'Šance přeskočit odpočinek po úspěšné expedici a ihned začít další.'
  ],
  influencer: [
    'Shares Expedition XP with other hamsters, even after failure. The first percentage is own XP, the second is shared XP.', 'Başarısızlıkta da sefer deneyimini diğer hamsterlarla paylaşır. İlk yüzde kendi deneyimini, ikinci yüzde paylaşılan deneyimi gösterir.', 'Делится опытом экспедиции даже при провале. Первый процент — собственный опыт, второй — опыт другим хомякам.', 'Teilt Expeditions-EP auch bei Fehlschlägen. Der erste Wert ist eigene EP, der zweite geteilte EP.', 'Comparte XP incluso si falla. El primer porcentaje es XP propia y el segundo XP compartida.', 'Partage les XP même en cas d’échec. Le premier pourcentage concerne ses XP, le second ceux partagés.', 'Compartilha XP mesmo ao falhar. A primeira porcentagem é XP própria; a segunda é compartilhada.', 'Membagikan XP meski gagal. Persentase pertama adalah XP sendiri, yang kedua XP untuk hamster lain.', '即使远征失败也分享经验。第一个百分比为自身经验，第二个为分享给其他仓鼠的经验。', 'Sdílí zkušenosti i při neúspěchu. První procento je vlastní zkušenost, druhé sdílená.'
  ],
  influencerShared: [
    'Shares the displayed percentage of Expedition XP with other hamsters.', 'Sefer deneyiminin belirtilen yüzdesini diğer hamsterlarla paylaşır.', 'Делится указанным процентом опыта экспедиции с другими хомяками.', 'Teilt den angegebenen Anteil der Expeditions-EP mit anderen Hamstern.', 'Comparte el porcentaje indicado de XP de expedición con otros hámsters.', 'Partage le pourcentage indiqué des XP d’expédition avec les autres hamsters.', 'Compartilha a porcentagem indicada da XP de expedição com outros hamsters.', 'Membagikan persentase XP Ekspedisi yang ditampilkan kepada hamster lain.', '将所示百分比的远征经验分享给其他仓鼠。', 'Sdílí uvedené procento zkušeností z expedice s ostatními křečky.'
  ],
  buyback: [
    'Changes the cost of reclaiming loot after a failed Expedition. Negative values make Buyback cheaper.', 'Başarısız sefer sonrası ganimeti geri alma maliyetini değiştirir. Negatif değer geri almayı ucuzlatır.', 'Меняет стоимость выкупа добычи после провала. Отрицательное значение делает выкуп дешевле.', 'Ändert die Rückkaufkosten der Beute nach Fehlschlägen. Negative Werte senken sie.', 'Modifica el coste de recuperar botín tras un fallo. Los valores negativos abaratan la recompra.', 'Modifie le coût de récupération du butin après un échec. Les valeurs négatives le réduisent.', 'Altera o custo de recuperar saque após falhar. Valores negativos barateiam a recompra.', 'Mengubah biaya mengambil kembali jarahan setelah gagal. Nilai negatif menurunkan biaya Buyback.', '调整失败远征后赎回战利品的费用，负值会降低费用。', 'Mění cenu výkupu kořisti po neúspěchu. Záporné hodnoty výkup zlevňují.'
  ],
  remoteBonus: [
    'While alive on an Expedition, grants room bonus equal to total hamster stats × the ability percentage.', 'Seferde hayattayken toplam hamster statı × yetenek yüzdesi kadar oda bonusu verir.', 'Пока хомяк жив в экспедиции, бонус комнате равен сумме характеристик × процент способности.', 'Solange der Hamster lebt, erhält der Raum Gesamtwerte × Fähigkeitsprozentsatz als Bonus.', 'Mientras vive en expedición, da una bonificación de sala igual a estadísticas totales × porcentaje.', 'Tant qu’il survit en expédition, le bonus de salle vaut total des stats × pourcentage.', 'Enquanto vive na expedição, o bônus da sala é atributos totais × porcentagem da habilidade.', 'Selama hidup dalam Ekspedisi, bonus ruangan = total statistik × persentase kemampuan.', '远征中存活期间提供房间加成：仓鼠属性总和 × 技能百分比。', 'Dokud žije na expedici, bonus místnosti = součet statistik × procento schopnosti.'
  ],
  remotePower: [
    'Temporarily adds Miner Power × the ability multiplier to your room, independently of room bonus percentages.', 'Odaya geçici olarak madenci gücü × yetenek çarpanı ekler; oda bonus yüzdelerinden bağımsızdır.', 'Временно добавляет комнате мощность майнеров × множитель, независимо от процентных бонусов.', 'Fügt vorübergehend Miner-Leistung × Multiplikator hinzu, unabhängig vom Raum-Bonusprozentsatz.', 'Añade potencia temporal de mineros × multiplicador, independiente de los porcentajes de sala.', 'Ajoute temporairement puissance des mineurs × multiplicateur, sans appliquer le bonus de salle.', 'Adiciona potência temporária dos mineradores × multiplicador, independente do bônus percentual da sala.', 'Menambahkan daya penambang × pengali untuk sementara, terpisah dari persentase bonus ruangan.', '临时增加矿机算力 × 技能倍数，不受房间百分比加成影响。', 'Dočasně přidá výkon těžařů × násobitel, nezávisle na procentních bonusech místnosti.'
  ],
  rltChest: [
    'Adds an extra RLT chest when the Expedition succeeds.', 'Sefer başarılı olursa ek bir RLT sandığı verir.', 'Добавляет сундук RLT при успешной экспедиции.', 'Fügt bei erfolgreicher Expedition eine RLT-Truhe hinzu.', 'Añade un cofre RLT si la expedición tiene éxito.', 'Ajoute un coffre RLT si l’expédition réussit.', 'Adiciona um baú RLT se a expedição tiver sucesso.', 'Menambah peti RLT jika Ekspedisi berhasil.', '远征成功时增加一个RLT宝箱。', 'Při úspěšné expedici přidává truhlu RLT.'
  ],
  seasonXpChest: [
    'Adds a special Season XP chest after a successful Expedition.', 'Başarılı seferin ödüllerine özel bir sezon deneyimi sandığı ekler.', 'Добавляет сундук сезонного опыта после успешной экспедиции.', 'Fügt nach erfolgreicher Expedition eine Saison-EP-Truhe hinzu.', 'Añade un cofre de XP de temporada tras una expedición exitosa.', 'Ajoute un coffre d’XP de saison après une expédition réussie.', 'Adiciona um baú de XP de temporada após uma expedição bem-sucedida.', 'Menambah peti XP Musim setelah Ekspedisi berhasil.', '成功远征后增加一个赛季经验宝箱。', 'Po úspěšné expedici přidává truhlu sezónních zkušeností.'
  ],
  keepGoing: [
    'No rest after success; after failure, rest lasts three times the normal duration.', 'Başarılı seferden sonra dinlenmez; başarısızlıkta normal sürenin üç katı dinlenir.', 'Не отдыхает после успеха; после провала отдых длится втрое дольше.', 'Keine Ruhe nach Erfolg; bei Fehlschlag dreifache normale Ruhezeit.', 'Sin descanso tras el éxito; si falla, descansa el triple de lo normal.', 'Aucun repos après réussite ; après échec, repos trois fois plus long.', 'Sem descanso após sucesso; ao falhar, descansa três vezes mais.', 'Tanpa istirahat setelah berhasil; jika gagal, istirahat tiga kali durasi normal.', '成功后无需休息；失败后休息时间为正常时长的三倍。', 'Po úspěchu bez odpočinku; po neúspěchu trojnásobná běžná doba odpočinku.'
  ],
  restRelay: [
    'Each full Expedition hour reduces other hamsters’ rest by the displayed minutes. Speed-Ups add no bonus; unused recovery is discarded.', 'Seferdeki her tam saat, diğer hamsterların dinlenmesini belirtilen dakika kadar azaltır. Hızlandırmalar ek bonus vermez; fazla toparlanma kullanılmaz.', 'Каждый полный час сокращает отдых других хомяков на указанные минуты. Ускорения не добавляют бонус; избыток теряется.', 'Jede volle Expeditionsstunde verkürzt die Ruhe anderer Hamster um die angegebenen Minuten. Keine zusätzlichen Boni durch Beschleuniger; Überschuss verfällt.', 'Cada hora completa reduce el descanso de otros hámsters en los minutos indicados. Los aceleradores no añaden beneficio; el sobrante se pierde.', 'Chaque heure complète réduit le repos des autres hamsters des minutes indiquées. Pas de bonus des accélérateurs ; surplus perdu.', 'Cada hora completa reduz o descanso dos outros hamsters pelos minutos indicados. Aceleradores não dão bônus; excedente é perdido.', 'Setiap jam penuh mengurangi istirahat hamster lain sesuai menit yang ditampilkan. Percepatan tidak menambah bonus; kelebihan terbuang.', '每个完整远征小时按所示分钟数减少其他仓鼠的休息。加速道具不增加效果，多余恢复量作废。', 'Každá celá hodina snižuje odpočinek ostatních o uvedené minuty. Zrychlení nepřidává bonus; přebytek propadá.'
  ],
  chargeRelay: [
    'Recharges other hamsters’ Ultimates from full original Expedition hours. Charge is rounded to whole points; Speed-Ups give no extra benefit.', 'Seferin tam orijinal saatleriyle diğer hamsterların ultisini şarj eder. Şarj tam puana yuvarlanır; hızlandırmalar ek yarar sağlamaz.', 'Заряжает ультимейты других хомяков за полные исходные часы. Заряд считается целыми очками; ускорения не дают прибавки.', 'Lädt Ultimates anderer Hamster anhand voller ursprünglicher Stunden. Nur ganze Ladepunkte; kein Zusatznutzen durch Beschleuniger.', 'Recarga las definitivas de otros hámsters con horas completas originales. Solo puntos enteros; los aceleradores no dan beneficio extra.', 'Recharge les ultimes des autres hamsters selon les heures originales complètes. Points entiers uniquement ; aucun bonus des accélérateurs.', 'Recarrega supremas dos outros hamsters com horas completas originais. Apenas pontos inteiros; aceleradores não dão benefício extra.', 'Mengisi ultimate hamster lain dari jam asli penuh. Poin daya berupa bilangan bulat; percepatan tidak menambah manfaat.', '按完整的原始远征小时为其他仓鼠的终极技能充能。仅计整数充能点，加速不提供额外效果。', 'Nabíjí ultimátní schopnosti ostatních za celé původní hodiny. Jen celé body; zrychlení nedává další výhodu.'
  ],
  gamesBoost: [
    'Changes Games Boost by the displayed percentage. GFeast pairs this choice with a Buyback cost trade-off.', 'Oyun güçlendirmesini belirtilen yüzde kadar değiştirir. GFeast bu seçeneği geri alma maliyetiyle dengeler.', 'Меняет Games Boost на указанный процент. У GFeast этот выбор связан с изменением цены выкупа.', 'Ändert Games Boost um den angegebenen Prozentsatz. Bei GFeast ist dies mit Rückkaufkosten verbunden.', 'Modifica Games Boost en el porcentaje indicado. GFeast lo combina con un cambio del coste de recompra.', 'Modifie Games Boost du pourcentage indiqué. Chez GFeast, ce choix change aussi le coût de rachat.', 'Altera Games Boost pela porcentagem indicada. GFeast combina essa opção com alteração do custo de recompra.', 'Mengubah Games Boost sesuai persentase. GFeast memasangkannya dengan perubahan biaya Buyback.', '按所示百分比调整游戏增益；GFeast的此选项同时改变赎回费用。', 'Mění Games Boost o uvedené procento. U GFeast je tato volba spojena se změnou výkupní ceny.'
  ],
  boostMode: [
    'Sets health, strength and luck to 100 for one Expedition when activated. Recharge requires {{charge}} points.', 'Etkinleştirildiğinde bir sefer boyunca can, güç ve şansın her birini 100 yapar. Yeniden kullanım için {{charge}} şarj puanı gerekir.', 'При активации здоровье, сила и удача становятся 100 на одну экспедицию. Для повторного использования нужно {{charge}} очков.', 'Setzt Gesundheit, Stärke und Glück für eine Expedition auf je 100. Erneutes Aufladen: {{charge}} Punkte.', 'Establece salud, fuerza y suerte en 100 durante una expedición. Recarga: {{charge}} puntos.', 'Fixe santé, force et chance à 100 pour une expédition. Recharge : {{charge}} points.', 'Define vida, força e sorte como 100 por uma expedição. Recarga: {{charge}} pontos.', 'Mengatur kesehatan, kekuatan dan keberuntungan masing-masing ke 100 untuk satu Ekspedisi. Isi ulang: {{charge}} poin.', '激活后一次远征中的生命、力量和幸运各为100。再次使用需{{charge}}充能点。', 'Nastaví zdraví, sílu a štěstí na 100 pro jednu expedici. Dobití: {{charge}} bodů.'
  ],
  chestsMultiplier: [
    'Activate before an Expedition, then select up to five rewards at the end and triple each. Recharge: {{charge}} points.', 'Sefer öncesinde etkinleştir; sefer sonunda en fazla beş ödül seçip her birini üçe katla. Şarj: {{charge}} puan.', 'Активируйте перед экспедицией; в конце выберите до пяти наград и утройте каждую. Заряд: {{charge}} очков.', 'Vor der Expedition aktivieren; danach bis zu fünf Belohnungen auswählen und verdreifachen. Aufladen: {{charge}} Punkte.', 'Activa antes de la expedición; al terminar, elige hasta cinco recompensas y triplica cada una. Recarga: {{charge}} puntos.', 'Activez avant l’expédition ; à la fin, choisissez jusqu’à cinq récompenses et triplez-les. Recharge : {{charge}} points.', 'Ative antes da expedição; ao final, escolha até cinco recompensas e triplique cada uma. Recarga: {{charge}} pontos.', 'Aktifkan sebelum Ekspedisi; di akhir pilih hingga lima hadiah dan lipat tigakan masing-masing. Isi ulang: {{charge}} poin.', '远征前激活，结束时选择最多五份奖励，每份变为三倍。充能：{{charge}}点。', 'Aktivujte před expedicí; na konci vyberte až pět odměn a každou ztrojnásobte. Dobití: {{charge}} bodů.'
  ],
  plagueChests: [
    'Triples up to five chosen rewards, even if the Expedition fails. Does not boost survival chance. Recharge: 30 points.', 'Sefer başarısız olsa da seçilen en fazla beş ödülü üçe katlar. Hayatta kalma olasılığını artırmaz. Şarj: 30 puan.', 'Утраивает до пяти выбранных наград даже при провале. Не повышает шанс выживания. Заряд: 30 очков.', 'Verdreifacht bis zu fünf gewählte Belohnungen auch bei Fehlschlag. Kein Überlebensbonus. Aufladen: 30 Punkte.', 'Triplica hasta cinco recompensas elegidas incluso si falla. No aumenta la supervivencia. Recarga: 30 puntos.', 'Triple jusqu’à cinq récompenses choisies, même en cas d’échec. Aucun bonus de survie. Recharge : 30 points.', 'Triplica até cinco recompensas escolhidas mesmo ao falhar. Não aumenta a sobrevivência. Recarga: 30 pontos.', 'Melipat tigakan hingga lima hadiah pilihan meski gagal. Tidak meningkatkan peluang bertahan hidup. Isi ulang: 30 poin.', '即使远征失败，也将最多五份选中奖励变为三倍。不提高生存概率。充能：30点。', 'Ztrojnásobí až pět vybraných odměn i při neúspěchu. Nezvyšuje přežití. Dobití: 30 bodů.'
  ],
  cryptoChest: [
    'Activate before an Expedition. A successful Expedition grants a Crypto Chest with cryptocurrency rewards. Recharge: {{charge}} points.', 'Sefer öncesinde etkinleştirilir. Başarılı sefer, kripto para ödülleri içeren bir sandık verir. Şarj: {{charge}} puan.', 'Активируйте перед экспедицией. При успехе выдаётся сундук с криптовалютой. Заряд: {{charge}} очков.', 'Vor der Expedition aktivieren. Bei Erfolg gibt es eine Krypto-Truhe. Aufladen: {{charge}} Punkte.', 'Activa antes de la expedición. Si tiene éxito, recibes un cofre de criptomonedas. Recarga: {{charge}} puntos.', 'Activez avant l’expédition. En cas de réussite, recevez un coffre de cryptomonnaies. Recharge : {{charge}} points.', 'Ative antes da expedição. Ao ter sucesso, receba um baú de criptomoedas. Recarga: {{charge}} pontos.', 'Aktifkan sebelum Ekspedisi. Jika berhasil, mendapat peti hadiah kripto. Isi ulang: {{charge}} poin.', '远征前激活，成功后获得装有加密货币奖励的宝箱。充能：{{charge}}点。', 'Aktivujte před expedicí. Při úspěchu získáte truhlu s kryptoměnami. Dobití: {{charge}} bodů.'
  ],
  sureWin: [
    'Guarantees success on the next Expedition. That run earns no charge points; charge resets to zero afterward.', 'Sonraki seferin başarısını garanti eder. Bu sefer şarj puanı kazandırmaz; sefer sonunda şarj sıfırlanır.', 'Гарантирует успех следующей экспедиции. Она не даёт заряд; после неё заряд обнуляется.', 'Garantiert Erfolg bei der nächsten Expedition. Sie gibt keine Ladepunkte; danach wird die Ladung zurückgesetzt.', 'Garantiza el éxito en la siguiente expedición. No genera carga; después la carga vuelve a cero.', 'Garantit la réussite de la prochaine expédition. Aucun point de charge gagné ; charge remise à zéro ensuite.', 'Garante sucesso na próxima expedição. Ela não gera carga; a carga volta a zero depois.', 'Menjamin Ekspedisi berikutnya berhasil. Perjalanan itu tidak menghasilkan poin daya; daya kembali nol setelahnya.', '保证下一次远征成功。该次远征不产生充能点，结束后充能归零。', 'Zaručuje úspěch další expedice. Ta nedává body nabití; poté se nabití vynuluje.'
  ],
  partsChest: [
    'Generates a Common Parts Chest through Expeditions, providing parts for miner upgrades.', 'Seferlerden common parça sandığı getirerek madenci geliştirmelerinde kullanılacak parçalar sağlar.', 'Даёт сундук обычных деталей через экспедиции для улучшения майнеров.', 'Erzeugt durch Expeditionen eine Truhe gewöhnlicher Teile für Miner-Upgrades.', 'Genera un cofre de piezas comunes en expediciones para mejorar mineros.', 'Génère un coffre de pièces communes en expédition pour améliorer les mineurs.', 'Gera um baú de peças comuns nas expedições para melhorar mineradores.', 'Menghasilkan peti Common Parts dari Ekspedisi untuk meningkatkan penambang.', '通过远征生成普通零件宝箱，用于升级矿机。', 'Z expedic získává truhlu běžných součástek pro vylepšení těžařů.'
  ],
  smartStudy: [
    'After activation, no rest is needed; each successful Expedition grants one permanent extra stat point beyond leveling. Stats can eventually reach 100 each.', 'Etkinleştirildikten sonra dinlenme gerekmez; her başarılı sefer, seviyeden bağımsız bir kalıcı ek stat puanı verir. Her stat zamanla 100’e ulaşabilir.', 'После активации отдых не нужен; каждый успех даёт постоянное дополнительное очко сверх уровней. Все характеристики со временем могут достичь 100.', 'Nach Aktivierung keine Ruhezeit; jeder Erfolg gibt einen permanenten zusätzlichen Punkt unabhängig vom Level. Jeder Wert kann langfristig 100 erreichen.', 'Tras activarse no necesita descanso; cada éxito da un punto permanente adicional al nivel. Cada estadística puede alcanzar 100 con el tiempo.', 'Après activation, aucun repos ; chaque réussite donne un point permanent en plus des niveaux. Chaque stat peut atteindre 100 avec le temps.', 'Após ativação, sem descanso; cada sucesso dá um ponto permanente além dos níveis. Cada atributo pode chegar a 100 com o tempo.', 'Setelah diaktifkan, tanpa istirahat; setiap keberhasilan memberi satu poin permanen di luar kenaikan level. Setiap statistik dapat mencapai 100 seiring waktu.', '激活后无需休息，每次成功远征获得一个独立于升级的永久额外属性点。各项属性可逐渐达到100。', 'Po aktivaci bez odpočinku; každý úspěch přidá trvalý bod navíc mimo levelování. Každá statistika může časem dosáhnout 100.'
  ],
  speedChest: [
    'Generates Speed-Up rewards usable on any hamster. Recharges in three Expedition hours.', 'Herhangi bir hamsterda kullanılabilen hızlandırma ödülleri verir. Üç sefer saatiyle yeniden şarj olur.', 'Даёт ускорения для любого хомяка. Перезарядка за три часа экспедиций.', 'Gibt Beschleuniger für jeden Hamster. Aufladen in drei Expeditionsstunden.', 'Da aceleradores utilizables en cualquier hámster. Recarga en tres horas de expedición.', 'Donne des accélérateurs pour tout hamster. Recharge en trois heures d’expédition.', 'Dá aceleradores utilizáveis em qualquer hamster. Recarga em três horas de expedição.', 'Memberi hadiah percepatan untuk hamster mana pun. Isi ulang dalam tiga jam Ekspedisi.', '提供可用于任意仓鼠的加速奖励，三个远征小时即可充能。', 'Dává zrychlení pro libovolného křečka. Dobití za tři hodiny expedic.'
  ],
  highRisk: [
    'Doubles rewards and XP, makes the run 1.5× longer and skips rest. On failure, salvaged rewards stay doubled, recovery takes 2× time and Buyback cost stays unchanged.', 'Ödül ve deneyimi ikiye, süreyi 1,5 kata çıkarır; dinlenmeyi atlar. Başarısızlıkta kurtarılan ödüller iki kat kalır, toparlanma süresi iki kat olur; geri alma maliyeti değişmez.', 'Удваивает награды и опыт, длительность ×1,5, без отдыха. При провале спасённые награды удвоены, восстановление ×2, цена выкупа прежняя.', 'Doppelte Beute und EP, Dauer ×1,5, keine Ruhe. Bei Fehlschlag bleiben gerettete Belohnungen doppelt, Erholungszeit ×2, Rückkaufpreis unverändert.', 'Duplica recompensas y XP, duración ×1,5 y sin descanso. Si falla, el botín recuperado sigue doble, recuperación ×2 y recompra sin cambios.', 'Double récompenses et XP, durée ×1,5, aucun repos. En cas d’échec, butin récupéré doublé, récupération ×2, rachat inchangé.', 'Dobra recompensas e XP, duração ×1,5 e sem descanso. Ao falhar, saque recuperado continua dobrado, recuperação ×2 e recompra inalterada.', 'Menggandakan hadiah dan XP, durasi ×1,5, tanpa istirahat. Jika gagal, hadiah terselamatkan tetap ganda, pemulihan ×2 dan biaya Buyback tetap.', '奖励与经验翻倍，时长变为1.5倍并跳过休息。失败时赎回奖励仍翻倍，恢复时间为2倍，赎回费用不变。', 'Dvojnásobné odměny a zkušenosti, doba ×1,5, bez odpočinku. Při neúspěchu zachráněné odměny zůstávají dvojité, zotavení ×2, výkupní cena stejná.'
  ],
  lootConversion: [
    'After an Expedition, choose which rewards to keep and which to convert into RLT at their technical value. Recharge: {{charge}} points.', 'Seferden sonra hangi ödüllerin kalacağını, hangilerinin teknik değerleri üzerinden RLT’ye dönüşeceğini seçersin. Şarj: {{charge}} puan.', 'После экспедиции выбирайте, что оставить, а что превратить в RLT по технической стоимости. Заряд: {{charge}} очков.', 'Nach der Expedition wählen, welche Belohnungen bleiben und welche zum technischen Wert in RLT umgewandelt werden. Aufladen: {{charge}} Punkte.', 'Tras la expedición elige qué guardar y qué convertir en RLT según su valor técnico. Recarga: {{charge}} puntos.', 'Après l’expédition, choisissez les récompenses à garder ou à convertir en RLT à leur valeur technique. Recharge : {{charge}} points.', 'Após a expedição, escolha o que manter ou converter em RLT pelo valor técnico. Recarga: {{charge}} pontos.', 'Setelah Ekspedisi, pilih hadiah untuk disimpan atau dikonversi ke RLT menurut nilai teknisnya. Isi ulang: {{charge}} poin.', '远征后选择保留哪些奖励、将哪些按技术价值转换为RLT。充能：{{charge}}点。', 'Po expedici vyberte odměny k ponechání nebo převodu na RLT dle technické hodnoty. Dobití: {{charge}} bodů.'
  ],
  overchargedConversion: [
    'Completed tiers convert 2 / 3 / 5 rewards into RLT for 24 / 30 / 36 points. Partial tiers do not count. Original Expedition hours charge it; use resets charge.', 'Tamamlanan kademeler 24 / 30 / 36 puanla 2 / 3 / 5 ödülü RLT’ye çevirir. Eksik kademe sayılmaz. Orijinal sefer saatleriyle şarj olur; kullanımda şarj sıfırlanır.', 'Полные уровни: 2 / 3 / 5 наград в RLT за 24 / 30 / 36 очков. Неполные не учитываются. Заряд от исходных часов; после использования сброс.', 'Vollständige Stufen: 2 / 3 / 5 Belohnungen in RLT für 24 / 30 / 36 Punkte. Teilstufen zählen nicht. Ursprüngliche Stunden laden; Nutzung setzt zurück.', 'Niveles completos: 2 / 3 / 5 recompensas a RLT por 24 / 30 / 36 puntos. Los parciales no cuentan. Carga con horas originales; se reinicia al usar.', 'Paliers complets : 2 / 3 / 5 récompenses en RLT pour 24 / 30 / 36 points. Paliers partiels ignorés. Heures originales pour la charge ; remise à zéro après usage.', 'Níveis completos: 2 / 3 / 5 recompensas em RLT por 24 / 30 / 36 pontos. Parciais não contam. Carga por horas originais; uso zera a carga.', 'Tingkat penuh: 2 / 3 / 5 hadiah ke RLT dengan 24 / 30 / 36 poin. Tingkat parsial tidak dihitung. Jam asli mengisi daya; penggunaan meresetnya.', '完整等级以24 / 30 / 36点将2 / 3 / 5份奖励转换为RLT。未完成等级不计。按原始远征小时充能，使用后归零。', 'Dokončené stupně: 2 / 3 / 5 odměn na RLT za 24 / 30 / 36 bodů. Částečné se nepočítají. Nabíjení původními hodinami; použití vynuluje nabití.'
  ],
  overchargedChests: [
    'Completed tiers triple 3 / 5 / 8 rewards for 18 / 24 / 30 points. Partial tiers do not count. Original Expedition hours charge it; use resets charge.', 'Tamamlanan kademeler 18 / 24 / 30 puanla 3 / 5 / 8 ödülü üçe katlar. Eksik kademe sayılmaz. Orijinal sefer saatleriyle şarj olur; kullanımda şarj sıfırlanır.', 'Полные уровни утраивают 3 / 5 / 8 наград за 18 / 24 / 30 очков. Неполные не учитываются. Заряд от исходных часов; после использования сброс.', 'Vollständige Stufen verdreifachen 3 / 5 / 8 Belohnungen für 18 / 24 / 30 Punkte. Teilstufen zählen nicht. Ursprüngliche Stunden laden; Nutzung setzt zurück.', 'Niveles completos triplican 3 / 5 / 8 recompensas por 18 / 24 / 30 puntos. Los parciales no cuentan. Horas originales cargan; se reinicia al usar.', 'Paliers complets : 3 / 5 / 8 récompenses triplées pour 18 / 24 / 30 points. Paliers partiels ignorés. Charge par heures originales ; remise à zéro après usage.', 'Níveis completos triplicam 3 / 5 / 8 recompensas por 18 / 24 / 30 pontos. Parciais não contam. Carga por horas originais; uso zera a carga.', 'Tingkat penuh melipat tigakan 3 / 5 / 8 hadiah dengan 18 / 24 / 30 poin. Tingkat parsial tidak dihitung. Jam asli mengisi daya; penggunaan meresetnya.', '完整等级以18 / 24 / 30点将3 / 5 / 8份奖励变为三倍。未完成等级不计。按原始远征小时充能，使用后归零。', 'Dokončené stupně ztrojnásobí 3 / 5 / 8 odměn za 18 / 24 / 30 bodů. Částečné se nepočítají. Nabíjení původními hodinami; použití vynuluje nabití.'
  ],
  pirateLuck: [
    'After success, each reward you choose has a 50% chance to triple or disappear. Unselected rewards stay safe. Using it skips rest.', 'Başarılı seferden sonra seçtiğin her ödül %50 ihtimalle üçe katlanır veya kaybolur. Seçilmemiş ödüller korunur. Kullanım dinlenmeyi atlar.', 'После успеха выбранные награды с шансом 50% утраиваются или исчезают. Невыбранные безопасны. Использование отменяет отдых.', 'Nach Erfolg wird jede gewählte Belohnung mit 50% Chance verdreifacht oder gelöscht. Ungewählte bleiben sicher. Nutzung überspringt Ruhe.', 'Tras el éxito, cada recompensa elegida tiene 50% de triplicarse o desaparecer. Las demás quedan seguras. El uso omite el descanso.', 'Après réussite, chaque récompense choisie a 50% de chance d’être triplée ou perdue. Les autres sont préservées. Utilisation sans repos.', 'Após sucesso, cada recompensa escolhida tem 50% de triplicar ou sumir. As demais ficam seguras. O uso elimina o descanso.', 'Setelah berhasil, setiap hadiah pilihan berpeluang 50% menjadi tiga kali atau hilang. Hadiah lain aman. Penggunaan melewati istirahat.', '成功后，每份选中奖励有50%概率变为三倍或消失。未选奖励安全保留。使用后跳过休息。', 'Po úspěchu má každá vybraná odměna 50% šanci ztrojnásobit se nebo zmizet. Ostatní zůstávají bezpečné. Použití přeskočí odpočinek.'
  ],
  hamstersChest: [
    'The next successful Expedition adds a chest containing Magic Wool or a hamster. Failure consumes the Ultimate without that chest. Recharge: 100 points.', 'Sonraki başarılı sefer, Magic Wool veya hamster içeren ek sandık verir. Başarısızlıkta ulti bu sandığı vermeden tükenir. Şarj: 100 puan.', 'Следующая успешная экспедиция даёт сундук с Magic Wool или хомяком. При провале ультимейт расходуется без сундука. Заряд: 100 очков.', 'Nächste erfolgreiche Expedition: Zusatztruhe mit Magic Wool oder Hamster. Bei Fehlschlag ohne Truhe verbraucht. Aufladen: 100 Punkte.', 'La siguiente expedición exitosa añade un cofre con Magic Wool o un hámster. El fallo consume la definitiva sin cofre. Recarga: 100 puntos.', 'La prochaine réussite ajoute un coffre contenant Magic Wool ou un hamster. Un échec consomme l’ultime sans coffre. Recharge : 100 points.', 'A próxima expedição bem-sucedida adiciona baú com Magic Wool ou hamster. Falhar consome a suprema sem baú. Recarga: 100 pontos.', 'Ekspedisi berhasil berikutnya menambah peti berisi Magic Wool atau hamster. Kegagalan menghabiskan ultimate tanpa peti. Isi ulang: 100 poin.', '下一次成功远征增加装有Magic Wool或仓鼠的宝箱。失败会消耗技能且不生成宝箱。充能：100点。', 'Další úspěšná expedice přidá truhlu s Magic Wool nebo křečkem. Neúspěch spotřebuje schopnost bez truhly. Dobití: 100 bodů.'
  ],
  remotePowerUltimate: [
    'While GFeast is alive on the Expedition, adds temporary Miner Power ×5 without room bonus multipliers. Duration uses original Expedition time, unaffected by Speed-Ups or time reductions.', 'GFeast seferde hayattayken, oda bonusuyla çarpılmayan geçici madenci gücü ×5 ekler. Süre orijinal sefer süresidir; hızlandırma ve süre azaltımı bunu değiştirmez.', 'Пока GFeast жив, добавляет временную мощность майнеров ×5 без бонусов комнаты. Срок — исходное время, ускорения и сокращения не влияют.', 'Solange GFeast lebt, temporäre Miner-Leistung ×5 ohne Raum-Multiplikatoren. Dauer nach ursprünglicher Expedition; Beschleuniger und Verkürzungen ändern sie nicht.', 'Mientras GFeast vive, añade potencia temporal ×5 sin bonus de sala. Duración original; aceleradores y reducciones no la cambian.', 'Tant que GFeast vit, puissance temporaire des mineurs ×5 sans bonus de salle. Durée originale, inchangée par accélérateurs ou réductions.', 'Enquanto GFeast vive, adiciona potência temporária ×5 sem bônus da sala. Duração original, sem efeito de aceleradores ou reduções.', 'Selama GFeast hidup, menambah daya penambang sementara ×5 tanpa pengali ruangan. Durasi asli tidak berubah oleh percepatan atau pengurangan waktu.', 'GFeast远征中存活期间增加临时矿机算力×5，不乘房间加成。持续时间按原始远征时长计算，不受加速或时长缩减影响。', 'Dokud GFeast žije, přidává dočasný výkon těžařů ×5 bez bonusu místnosti. Trvání dle původní doby, bez vlivu zrychlení a zkrácení.'
  ],
};
const examples = {
  cuscuzRemoteBonus: [
    'Base stats: (90 + 75 + 90) ×2% = 510% room bonus.',
    'Temel statlar: (90 + 75 + 90) ×%2 = %510 oda bonusu.',
    'Базовые характеристики: (90 + 75 + 90) ×2% = 510% бонуса комнаты.',
    'Grundwerte: (90 + 75 + 90) ×2% = 510% Raumbonus.',
    'Estadísticas base: (90 + 75 + 90) ×2% = 510% de bonus de sala.',
    'Stats de base : (90 + 75 + 90) ×2 % = 510 % de bonus de salle.',
    'Atributos base: (90 + 75 + 90) ×2% = 510% de bônus de sala.',
    'Atribut dasar: (90 + 75 + 90) ×2% = 510% bonus ruangan.',
    '基础属性：(90 + 75 + 90) ×2% = 510%房间加成。',
    'Základní atributy: (90 + 75 + 90) ×2 % = 510% bonus místnosti.'
  ],
  remoteBonus: [
    'Base stats: (40 + 90 + 90) ×2% = 440%. At 100/100/100: 600%.', 'Temel statlar: (40 + 90 + 90) ×%2 = %440. 100/100/100 statta: %600.', 'Базовые: (40 + 90 + 90) ×2% = 440%. При 100/100/100: 600%.', 'Grundwerte: (40 + 90 + 90) ×2% = 440%. Bei 100/100/100: 600%.', 'Base: (40 + 90 + 90) ×2% = 440%. Con 100/100/100: 600%.', 'Base : (40 + 90 + 90) ×2% = 440%. Avec 100/100/100 : 600%.', 'Base: (40 + 90 + 90) ×2% = 440%. Com 100/100/100: 600%.', 'Dasar: (40 + 90 + 90) ×2% = 440%. Pada 100/100/100: 600%.', '基础属性：(40 + 90 + 90) ×2% = 440%。100/100/100时：600%。', 'Základ: (40 + 90 + 90) ×2% = 440%. Při 100/100/100: 600%.'
  ],
  overchargedChests: [
    'With 28 charge points, Tier II is complete: five rewards are tripled. Tier III needs 30.', '28 şarj puanında tamamlanan Kademe II kullanılır: beş ödül üçe katlanır. Kademe III için 30 gerekir.', 'При 28 очках готов уровень II: пять наград утраиваются. Для III нужно 30.', 'Mit 28 Punkten gilt Stufe II: fünf Belohnungen verdreifacht. Stufe III braucht 30.', 'Con 28 puntos se usa el nivel II: cinco recompensas triplicadas. El III necesita 30.', 'Avec 28 points, palier II : cinq récompenses triplées. Palier III : 30 requis.', 'Com 28 pontos, nível II: cinco recompensas triplicadas. O III precisa de 30.', 'Dengan 28 poin, tingkat II penuh: lima hadiah dilipat tigakan. Tingkat III perlu 30.', '28充能点使用已完成的II级：五份奖励变为三倍。III级需要30点。', 'S 28 body se použije stupeň II: pět odměn ztrojnásobeno. Stupeň III potřebuje 30.'
  ],
};
const labels = {
  remoteBonusUltimate: ['Remote Bonus', 'Uzaktan bonus', 'Удалённый бонус', 'Fernbonus', 'Bonificación remota', 'Bonus à distance', 'Bônus remoto', 'Bonus jarak jauh', '远程加成', 'Vzdálený bonus'],
  boostMode: ['Boost Mode', 'Güçlendirme modu', 'Режим усиления', 'Verstärkungsmodus', 'Modo de mejora', 'Mode de renforcement', 'Modo de reforço', 'Mode peningkatan', '强化模式', 'Režim posílení'],
  chestsMultiplier: ['Chests Multiplier ×3', 'Sandık çarpanı ×3', 'Множитель сундуков ×3', 'Truhenmultiplikator ×3', 'Multiplicador de cofres ×3', 'Multiplicateur de coffres ×3', 'Multiplicador de baús ×3', 'Pengali peti ×3', '宝箱倍率 ×3', 'Násobitel truhel ×3'],
  cryptoChest: ['Crypto Chest', 'Kripto para sandığı', 'Криптосундук', 'Krypto-Truhe', 'Cofre de criptomonedas', 'Coffre de cryptomonnaies', 'Baú de criptomoedas', 'Peti kripto', '加密货币宝箱', 'Truhla s kryptoměnami'],
  sureWin: ['Sure Win', 'Kesin zafer', 'Верная победа', 'Sicherer Sieg', 'Victoria segura', 'Victoire assurée', 'Vitória garantida', 'Kemenangan pasti', '必胜', 'Jisté vítězství'],
  partsChest: ['Common Parts Chest', 'Yaygın parça sandığı', 'Сундук обычных деталей', 'Truhe gewöhnlicher Teile', 'Cofre de piezas comunes', 'Coffre de pièces communes', 'Baú de peças comuns', 'Peti komponen umum', '普通零件宝箱', 'Truhla běžných součástek'],
  smartStudy: ['Smart Study', 'Akıllı çalışma', 'Умная учёба', 'Cleveres Lernen', 'Estudio inteligente', 'Étude intelligente', 'Estudo inteligente', 'Belajar cerdas', '聪明学习', 'Chytré studium'],
  speedChest: ['Speed Ups Chest', 'Hızlandırma sandığı', 'Сундук ускорений', 'Beschleunigertruhe', 'Cofre de aceleradores', 'Coffre d’accélérateurs', 'Baú de aceleradores', 'Peti percepatan', '加速宝箱', 'Truhla zrychlení'],
  highRisk: ['High Risk High Reward', 'Yüksek risk, yüksek ödül', 'Высокий риск, высокая награда', 'Hohes Risiko, hohe Belohnung', 'Alto riesgo, alta recompensa', 'Risque élevé, récompense élevée', 'Alto risco, alta recompensa', 'Risiko tinggi, hadiah besar', '高风险高回报', 'Vysoké riziko, vysoká odměna'],
  lootConversion: ['Loot Conversion', 'Ganimet dönüşümü', 'Конвертация добычи', 'Beuteumwandlung', 'Conversión de botín', 'Conversion du butin', 'Conversão de saque', 'Konversi jarahan', '战利品转换', 'Převod kořisti'],
  pirateLuck: ['Pirate Luck', 'Korsan şansı', 'Пиратская удача', 'Piratenglück', 'Suerte pirata', 'Chance de pirate', 'Sorte pirata', 'Keberuntungan bajak laut', '海盗运气', 'Pirátské štěstí'],
  hamstersChest: ['Hamsters Chest', 'Hamster sandığı', 'Сундук хомяков', 'Hamstertruhe', 'Cofre de hámsters', 'Coffre de hamsters', 'Baú de hamsters', 'Peti hamster', '仓鼠宝箱', 'Truhla křečků'],
  remotePowerUltimate: ['Remote Power', 'Uzaktan güç', 'Удалённая мощность', 'Fernleistung', 'Potencia remota', 'Puissance à distance', 'Potência remota', 'Daya jarak jauh', '远程算力', 'Vzdálený výkon'],
};
labels.overchargedChests = labels.chestsMultiplier;
labels.overchargedConversion = labels.lootConversion;
descriptions.gamesBoost = descriptions.gamesBoost.map(text => text.replace('GFeast', '{{name}}'));
for (const [group, entries] of Object.entries({ ui, labels, descriptions, examples })) {
  for (const [key, values] of Object.entries(entries)) {
    if (values.length !== languages.length || values.some(value => !value)) throw new Error(`Incomplete ${group}.${key}`);
  }
}
languages.forEach((language, index) => {
  const target = path.join(__dirname, '../src/locales', `${language}.json`);
  const locale = JSON.parse(fs.readFileSync(target, 'utf8'));
  const translate = entries => Object.fromEntries(Object.entries(entries).map(([key, values]) => [key, values[index]]));
  locale.hamsterAbilityGuide = { ...translate(ui), labels: translate(labels), descriptions: translate(descriptions), examples: translate(examples) };
  fs.writeFileSync(target, JSON.stringify(locale, null, 2) + '\n');
});
console.log(`Updated hamster ability guides in ${languages.length} languages.`);
