name: Deploy Rollercoin Frontend to VDS via GHCR

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Kodu Cek
        uses: actions/checkout@v7

      - name: GHCR Giris
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Kullanici adini kucuk harfe cevir
        run: echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Build ve Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/rollercoin-frontend:latest

      - name: Compose Dosyasini VDS'e Kopyala
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VDS_IP }}
          username: ${{ secrets.VDS_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/app/RollercoinCalculatorWeb"

      - name: VDS Deploy (SSH)
        uses: appleboy/ssh-action@v1.2.5
        env:
          REPO_OWNER: ${{ env.REPO_OWNER }}
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          host: ${{ secrets.VDS_IP }}
          username: ${{ secrets.VDS_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REPO_OWNER, GH_PAT
          script: |
            echo "$GH_PAT" | docker login ghcr.io -u "$REPO_OWNER" --password-stdin
            
            # Proje klasörünü oluştur (yoksa) ve içine gir
            mkdir -p /home/app/RollercoinCalculatorWeb
            cd /home/app/RollercoinCalculatorWeb
            
            # Dinamik imaj ismini .env dosyasına yazdır (Küçük harf garantisi)
            echo "IMAGE_TAG=ghcr.io/$REPO_OWNER/rollercoin-frontend:latest" > .env
            
            docker pull ghcr.io/$REPO_OWNER/rollercoin-frontend:latest
            
            # Sadece frontend servisini ayağa kaldır
            docker compose up -d --force-recreate rollercoin_frontend
            
            docker image prune -f